[project]
name = "clipsapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.2",
    "fastapi[standard]>=0.123.5",
    "pydantic>=2.12.5",
    "uvicorn>=0.38.0",
]
